SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

INSERT INTO f VALUES(35, 'Guías Básicas', 3729, '1. Guía de Progreso de Personaje', '[align=center][img]https://onepiecegaiden.com/images/op/uploads/GuiaProgreso_One_Piece_Gaiden_Foro_Rol.jpg[/img][/align]\r\n\r\nEn esta guía vamos a revisar el sistema de progreso en su conjunto, es decir, mostrar y orientar el proceso de progreso estándar de un personaje. Veremos todas las etapas de mejora por las que va a pasar tu personaje, en que consisten y la relación de lo que gastas y obtienes con cada avance.\r\n\r\nEntre los sistemas de progreso principales tenemos la subida de nivel, la subida atributos, la mejora de oficios, la creación objetos y el aprendizaje de técnicas.\r\n\r\n[img=13x13]https://onepiecegaiden.com/images/op/uploads/TituloDestacado_One_Piece_Gaiden_Foro_Rol.png[/img] [color=#ff8900][b][size=12]Monedas y Divisas[/size][/b][/color]\r\nLo más importante para entender todos los otros sistemas y mecánicas del foro serán los recursos que nos van a solicitar con el fin de acceder a ellas y progresar en las mismas.\r\n\r\n[spoiler=Experiencia]La [b][color=#8964dc]Experiencia (EXP) [/color][/b');
INSERT INTO f VALUES(35, 'Guías Básicas', 3733, '2. Guía de Temporalidad y Tipos de Tema', '[align=center][img]https://onepiecegaiden.com/images/op/uploads/GuiaTemas_One_Piece_Gaiden_Foro_Rol.jpg[/img][/align]\r\n\r\nCuando creamos [b]One Piece Gaiden[/b], lo hicimos con el objetivo de crear un mundo dinámico donde cada usuario sea una parte tangible y colateral de un entorno vivo. Buscamos que vosotros seáis los protagonistas, y como tal, también podáis tomar una parte ejecutiva del motor del foro, tanto con vuestros personajes como siendo narradores. Por ello, en esta guía explicaremos todos los tipos de tema que existen, así como la guía de narraciones acorde a ellos.\r\n\r\n[img=13x13]https://onepiecegaiden.com/images/op/uploads/TituloDestacado_One_Piece_Gaiden_Foro_Rol.png[/img] [color=#ff8900][size=12][b]Temporalidad y Presente[/b][/size][/color]\r\nExiste una fecha actual [b]On-Rol[/b] que determina en qué época se pueden tener temas en presente. Esta fecha se irá moviendo con el tiempo, siendo la administración la encargada de actualizarla y anunciarla. Dividiremos el avance del tiempo en ');
INSERT INTO f VALUES(35, 'Guías Básicas', 3736, '4. Guía de Oficios', '[align=center][img]https://onepiecegaiden.com/images/op/uploads/GuiaCrafteos_One_Piece_Gaiden_Foro_Rol.jpg[/img][/align]\r\n\r\nEn [b]One Piece Gaiden[/b], los oficios son una parte crucial de la experiencia, ofreciendo más que simples ventajas en el día a día de tu personaje. Además de influir en momentos específicos del rol, los oficios te permiten ser una pieza clave en la historia, realizar tareas únicas e impactar en la economía del foro. A través de los oficios, puedes crear objetos, gestionarlos, y decidir cómo usarlos, ya sea acumulándolos, regalándolos, vendiéndolos o incluso abriendo una tienda.\r\n\r\n[img=13x13]https://onepiecegaiden.com/images/op/uploads/TituloDestacado_One_Piece_Gaiden_Foro_Rol.png[/img] [color=#ff8900][b]Los Oficios[/b][/color]\r\nExisten 10 oficios en total y cada uno de ellos tiene 5 [i][color=#8964dc]Rangos[/color][/i]. Los dos primeros niveles son los básicos, mientras que los tres niveles restantes se enfocan en las especializaciones avanzadas. Más abajo te hablamos s');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
